services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # You can specify a custom Dockerfile if needed
    env_file:
      - .env  # Load environment variables from a .env file
    ports:
      - "80:80"  # Maps host port 8000 to container port 80
    volumes:
      - .:/var/www/html  # Syncs the current directory with the container
    user: "${UID}:${GID}"
    # depends_on:
    #   - db
  
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: ${DB_DATABASE}
  #     MYSQL_USER: ${DB_USERNAME}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #   ports:
  #     - "3306:3306"  # Expose the database
  #   volumes:
  #     - dbdata:/var/lib/mysql

volumes:
  dbdata:
